server:
  port: 8088
  shutdown: graceful

spring:
  llifecycle:
    timeout-per-shutdown-phase: 20s
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.37.42.105:3306/foodDelivery?serverTimezone=UTC&characterEncoding=UTF-8
    username: foodDel
    password: Qwer1234!@
  redis:
    host: "127.0.0.1"
    port: 6379
