server:
  port: 8088
  shutdown: graceful

spring:
  llifecycle:
    timeout-per-shutdown-phase: 20s
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.37.42.105:3306/foodDelivery?serverTimezone=UTC&characterEncoding=UTF-8
    username: foodDel
    password: Qwer1234!@
  redis:
    host: "127.0.0.1"
    port: 6379

  ## NANVER SENS
  sens-api:
    url: https://sens.apigw.ntruss.com/
    accessKey: BUw33p
    secretKey: 6WxdRYGsWYqU7
    from: "01011112222"
    type: SMS
    contentType: COMM
    countryCode: 82
    serviceId: ncp:sms:kr:26752:fooddelpjt

  ## java mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: 이메일
    password: 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


# payment
payment:
  method:
    kakao:
      apiKey: 'TC0ONETIME'
      partnerUserId : partner_user_id
      url: https://kapi.kakao.com/
      Authorization: 'KakaoAK {ADMIN-KEY}'
      ContentType: 'application/x-www-form-urlencoded;charset=utf-8'
      approvalUrl: http://localhost:8088
      cancelUrl: http://localhost:8088
      failUrl: http://localhost:8088